name: 'Post PR comment'
description: 'Post a comment in the PR with the given ID'
inputs:
  github_token:  # id of input
    description: 'Github token'
    required: true
    default: ''
runs:
  using: 'node12'
  main: 'index.js'