name: 'Post PR comment'
description: 'Post a comment in the PR with the given ID'
inputs:
  pull_request_id:  # id of input
    description: 'PR number'
    required: true
    default: ''
runs:
  using: 'node12'
  main: 'index.js'