on:
  push:
    branches:
      - master

jobs:
  update_app_settings_job:
    runs-on: ubuntu-latest
    name: Post comment to PR
    steps:
      - uses: actions/checkout@v1
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Upload the application settings
        id: upload_app_settings_id
        uses: GiridharanNarayanan/post-pr-comment@master
        with:
          pull_request_id: 1