on:
  pull_request:
    branches:
      - master

jobs:
  update_app_settings_job:
    runs-on: ubuntu-latest
    name: Post comment to PR
    steps:
      - name: Commenting on a PR
        id: upload_app_settings_id
        uses: GiridharanNarayanan/post-pr-comment@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}